[project]
name = "tastytrade-sdk"
version = "0.0.1"
authors = [
    { name = "Aaron Mamparo", email = "aaron.mamparo@gmail.com" },
]
description = "A python wrapper around the tastytrade open API"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/amamparo/tastytrade-sdk"
